### ISSUE TITLE
Subnet router ACL's broken on 0.23.0-alpha1

### ISSUE THREAD

**Issue by Sh4d** [juanfont/headscale#1604]
## Bug description

If you define an ACL on 0.23.0-alpha1, it breaks subnet routing. It works if you allow access to 0.0.0.0/0, but anything more specific just breaks traffic.

## Environment

Ubuntu server with headscale 0.23.0-alpha1 on public IP space
Ubuntu server with exit / subnet router on 1.52.1 on internal IP space
Windows test machine on 1.52.1

## To Reproduce

1. Bring linux subnet router online with:
```
 tailscale up --advertise-routes=10.33.0.0/16 --login-server=https://XXXXX --hostname=Test-Exit --reset
```
2. Enable the route on the headscale server + make sure ipforwarding is enabled on test-exit
3. Configure this ACL:
```
{
  "groups": {
    "group:admins": ["user1"],
  },
  "acls": [
    { "action": "accept", "src": ["group:admins"], "dst": ["group:admins:*"] },
    { "action": "accept", "src": ["group:admins"], "dst": ["10.33.0.0/16:*"] },
    { "action": "accept", "src": ["group:admins"], "dst": ["0.0.0.0/0:*"] },
  ]
}
```
4. Ping 10.33.10.10 from the windows test machine, confirm it works
5. Comment out the allow 0.0.0.0/0, and kill -HUP headscaled
6. See ping stops working
7. Uncomment 0.0.0.0/0 again, kill -HUP, ping starts working

This exact same config works fine on 0.22.3.

**Comment by kradalby** [comment]
[0.23.0-alpha2](https://github.com/juanfont/headscale/releases/tag/v0.23.0-alpha2) addresses a series of issues with node synchronisation, online status and subnet routers, please test this release and report back if the issue still persist.

**Comment by winterheart** [comment]
Hello, seems 0.23.0-alpha2 still has this issue. I've just updated and reverted back to 0.22.3 mine deployment due inability to use subnet routers. On 0.22.3 all works as expected.

**Comment by kfkawalec** [comment]
@jwischka Can you share your ACL? I have the same problem, only ACL with "*:0" helps but its not what I want.

**Comment by kfkawalec** [comment]
In my case:
- if user1 is the router, then user2 and user3 can connect through the router
- if user2 is the router, user1 can connet (*:*) but user3 cannot

**Comment by kradalby** [comment]
@Sh4d @kfkawalec 

Could you please get me a copy of the netmap from the nodes from both version 0.23.0-alpha2 and 0.22.3 so I can compare them?

You can do that with `tailscale debug netmap > netmap.json` for each node. I recon the most interesting node is the one that can no longer ping.

**Comment by kradalby** [comment]
I think I have fixed this in https://github.com/juanfont/headscale/pull/1673, could you try that PR?

**Comment by kfkawalec** [comment]
At the moment I do not have a 0.23.0-alpha2 installation.

**Comment by sniff122** [comment]
Not sure if its entirely related, however I am seeing broken subnet routes when setting an ACL. 

I have the following ACL:
```
"acls": [
            {
                "action": "accept",
                "src": [
                        "group:developers"
                ],
                "dst": [
                        "test-server"
                ]
            },
            {
                "action": "accept",
                "src": [
                        "group:developers"
                ],
                "dst": [
                        "group:developers:*"
                ]
            },
            {
                "action": "accept",
                "src": [
                    "*",
                    "group:internal-exitnode"
                ],
                "dst": [
                    "group:internal-exitnode:*"
                ]
            }
    ]
```

the test-server is defined as a host and is on the same subnet as a the "exit node" advertising the route for the subnet, it is enabled.

With this ACL config, i am not seeing the subnet route in the PacketFilterRules under DstPorts (still seeing the other 2 rules though). 

When setting a wildcard dst for the developer group, i am able to ping everything on the subnet and can see the wildcard in DstPorts in the PacketFilterRules. 

I have also tried @kradalby's #1673 with the same result.

Tried on MacOS, Windows and Linux clients with the exact same result, running a packet capture on the client for the tailscale interface shows the ICMP with no response found, running a wireshark sshdump on tailscale0 of the subnet route server, i see no ICMP packets

**Comment by kradalby** [comment]
@sniff122 does it work with 0.22.3? I just want to understand if it is already broken or a regression.

**Comment by sniff122** [comment]
@kradalby I believe I was having the issue that was fixed by #1564 which is in 0.23.0-alpha2, i shall try 0.22.3 again

**Comment by sniff122** [comment]
It doesnt look like i have a recent snapshot of my VM with 0.22.3 however with 0.23.0-alpha1 the issues are still present

**Comment by kradalby** [comment]
ok, I it would be ideal to get that tested as it will indicate if it is a new issue or an already existing one. 

If it is a new issue (since 0.22.3), it will block the new release, but if it is an existing issue, then we should create a separate issue and solve it after 0.23.0 goes out.

**Comment by nathan-march** [comment]
I just re-tested and confirmed this problem still happens with headscale_0.23.0-alpha2_linux_amd64.deb

**Comment by Sh4d** [comment]
I just tested and confirmed this issue still exists on headscale_0.23.0-alpha2_linux_amd64.deb

**Comment by Sh4d** [comment]
Here's a (slightly scrubbed) netmap from the client while broken. I was using the exact ACL at the top of this issue with just the allow 0.0.0.0 removed.

[netmap.txt](https://github.com/juanfont/headscale/files/13877293/netmap.txt)

**Comment by lewis-foster-reciteme** [comment]
> ok, I it would be ideal to get that tested as it will indicate if it is a new issue or an already existing one.
> 
> If it is a new issue (since 0.22.3), it will block the new release, but if it is an existing issue, then we should create a separate issue and solve it after 0.23.0 goes out.

@kradalby 

Just tested with 0.22.3, found an older backup and it ACLs appear to be working fine

**Comment by sniff122** [comment]
> ok, I it would be ideal to get that tested as it will indicate if it is a new issue or an already existing one.
> 
> If it is a new issue (since 0.22.3), it will block the new release, but if it is an existing issue, then we should create a separate issue and solve it after 0.23.0 goes out.

@kradalby

Just tested with 0.22.3, found an older backup and it ACLs appear to be working fine

**Comment by kradalby** [comment]
Could you give 0.23.0-alpha3 a go and report back?

**Comment by nathan-march** [comment]
My install is prod now unfortunately so I'll need to spin up a test environment. Hopefully can do that next week.

**Comment by Sh4d** [comment]
My install is prod now unfortunately so I'll need to spin up a test environment. Hopefully can do that next week.

**Comment by oneingan** [comment]
I am having the same problem with 0.23.0-alpha3
